# Generated by Django 5.2.4 on 2025-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_profile', 'Can view user profile')]},
        ),
    ]
